typography_spectrum: 0.5773694347590208
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.0035786530934274197
  lightness: 0.535985741764307
  saturation: 0.7244303040206432
  rhythmicContrast: 0.5531000734772533
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/c11d4a8b-9fa1-4a16-97cd-5845344e57c1.jpg
  type: null
  appId: null
layout_spectrum: 0.6020280160009861
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ammacentremauritius
  email: ammacentremauritius@gmail.com
  url: ammacentremauritius.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e369875b-215e-433d-bd92-ad6afc65d88e.jpg
name: Amma Centre Mauritius
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Amma (Mata Amritanandamayi)
    id: 4ddd7d95-85d7-4fc0-b519-271af1e7e7d0
    type: content
  - name: What People Say
    id: fa2620a9-21f5-4c4c-a2b7-a77edf1db8ad
    type: content
  - name: Awards & Honors
    id: 7c38cc28-d249-4bfb-b2e7-3d4064051191
    type: content
  - name: amma.org
    url: 'http://amma.org/'
    type: external
  - name: Amritapuri
    url: amritapuri.org
    type: external
  - name: Embracing the world
    url: 'http://www.embracingtheworld.org/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/356c4b42-5283-4385-be76-e6bac9e971d3.png
title: Amma Centre Mauritius
purpose: []
