typography_spectrum: 0.177095799241215
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.01407956425100565
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06601795880123973
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ammacentremauritius
  email: ammacentremauritius@gmail.com
  url: ammacentremauritius.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e369875b-215e-433d-bd92-ad6afc65d88e.jpg
name: Amma Centre Mauritius
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Amma (Mata Amritanandamayi)
    id: 4ddd7d95-85d7-4fc0-b519-271af1e7e7d0
    type: content
  - name: amma.org
    url: 'http://amma.org/'
    type: external
  - name: Amritapuri
    url: amritapuri.org
    type: external
  - name: Embracing the world
    url: 'http://www.embracingtheworld.org/'
    type: external
  - name: What People Say
    id: fa2620a9-21f5-4c4c-a2b7-a77edf1db8ad
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/356c4b42-5283-4385-be76-e6bac9e971d3.png
title: Amma Centre Mauritius
purpose: []
